# Generated by Django 4.0.4 on 2022-08-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Research group')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('summary', models.TextField()),
                ('pdf', models.FileField(upload_to='pdf')),
                ('category', models.ManyToManyField(related_name='papers', to='researchapp.researchcategory')),
            ],
        ),
    ]
