# Generated by Django 3.2.12 on 2022-09-10 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researchapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='university',
        ),
    ]
