# Generated by Django 3.2.12 on 2022-09-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='peerReview',
            field=models.FileField(null=True, upload_to='pdf/peerReview'),
        ),
    ]
