# Generated by Django 4.0.4 on 2022-08-16 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='group1_papers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paper',
            name='group2_papers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paper',
            name='group3_papers',
            field=models.BooleanField(default=False),
        ),
    ]
