# Generated by Django 4.0.4 on 2022-09-24 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researchapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='role_type',
            new_name='RoleType',
        ),
    ]
