# Generated by Django 3.2.12 on 2022-09-10 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researchapp', '0002_remove_groups_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grp',
            field=models.ForeignKey(default=None, null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, to='researchapp.groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default=None, null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, to='researchapp.role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uni',
            field=models.ForeignKey(default=None, null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, to='researchapp.university'),
        ),
    ]
