# Generated by Django 4.0.4 on 2022-09-22 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researchapp', '0002_paper_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='category',
        ),
        migrations.AddField(
            model_name='paper',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, to='researchapp.researchcategory'),
            preserve_default=b'I01\n',
        ),
    ]
