# Generated by Django 3.2.12 on 2022-09-20 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researchapp', '0002_alter_paper_peerreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='peerReview',
            field=models.FileField(blank=True, null=True, upload_to='pdf/peerReview'),
        ),
        migrations.AlterField(
            model_name='university',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='grp',
            field=models.ForeignKey(blank=True, default=None, null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, to='researchapp.groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, default=None, null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, to='researchapp.role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uni',
            field=models.ForeignKey(blank=True, default=None, null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, to='researchapp.university'),
        ),
    ]
