# Generated by Django 4.0.4 on 2022-08-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchapp', '0002_paper_group1_papers_paper_group2_papers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='summary',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='group1_papers',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='group2_papers',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='group3_papers',
        ),
        migrations.AddField(
            model_name='paper',
            name='co_author',
            field=models.CharField(default='ee', max_length=50),
            preserve_default=False,
        ),
    ]
