# Generated by Django 4.0.4 on 2022-08-18 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchapp', '0003_rename_summary_paper_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchcategory',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Type of paper'),
        ),
    ]
