# Generated by Django 3.2.12 on 2022-09-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchapp', '0003_auto_20220920_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_role',
            field=models.CharField(blank=True, choices=[('masters', 'masters'), ('phd', 'phd')], max_length=10, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
    ]
