# Generated by Django 3.2.12 on 2022-09-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchapp', '0003_rename_univeristy_user_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=b'I01\n', upload_to='images/profilePic'),
            preserve_default=b'I01\n',
        ),
    ]
