# Generated by Django 3.2.12 on 2022-09-10 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researchapp', '0003_auto_20220910_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='uni',
            field=models.ForeignKey(default=None, null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, to='researchapp.university'),
            preserve_default=b'I01\n',
        ),
    ]
