# Generated by Django 4.0.4 on 2022-09-16 15:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('researchapp', '0004_groups_uni'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
