# Generated by Django 3.2.12 on 2022-09-26 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researchapp', '0004_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='published_by',
            field=models.ForeignKey(blank=True, default=None, null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=b'I01\n',
        ),
    ]
