# Generated by Django 4.0.4 on 2022-09-23 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researchapp', '0004_paper_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='peerReview',
        ),
    ]
