# Generated by Django 3.2.12 on 2022-09-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchapp', '0004_groups_uni'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='image',
            field=models.ImageField(default=None, null=b'I01\n', upload_to='images'),
            preserve_default=b'I01\n',
        ),
    ]
