# Generated by Django 3.2.12 on 2022-09-24 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researchapp', '0004_user_student_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='student_role',
            field=models.ForeignKey(blank=True, default=None, null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, to='researchapp.studentrole'),
        ),
    ]
