# Generated by Django 4.0.4 on 2022-09-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchapp', '0005_remove_paper_peerreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='peerReview',
            field=models.FileField(blank=True, null=b'I01\n', upload_to='pdf/peerReview'),
            preserve_default=b'I01\n',
        ),
    ]
