# Generated by Django 4.0.4 on 2022-09-26 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researchapp', '0005_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='author_username',
            field=models.CharField(blank=True, default=None, max_length=50, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='paper',
            name='co_author_username',
            field=models.CharField(blank=True, default=None, max_length=50, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='paper',
            name='published_by',
            field=models.ForeignKey(blank=True, default=None, null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=b'I01\n', upload_to='images/profilePic'),
            preserve_default=b'I01\n',
        ),
    ]
