# Generated by Django 3.2.12 on 2022-09-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchapp', '0005_paper_published_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='author_username',
            field=models.CharField(blank=True, default=None, max_length=50, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='paper',
            name='co_author_username',
            field=models.CharField(blank=True, default=None, max_length=50, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
    ]
