# Generated by Django 4.0.4 on 2022-09-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchapp', '0006_rename_gname_groups_group_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
