# Generated by Django 4.0.4 on 2022-09-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchapp', '0006_paper_peerreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='description',
            field=models.CharField(default='hello', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=100, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
    ]
