# Generated by Django 3.2.12 on 2022-09-26 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researchapp', '0006_auto_20220926_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='author_username',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='co_author_username',
        ),
    ]
