# Generated by Django 3.2.12 on 2022-09-26 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchapp', '0006_paper_author_username_paper_co_author_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='author_username',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='co_author_username',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
