# Generated by Django 4.0.4 on 2022-09-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchapp', '0007_alter_paper_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
